### ISSUE TITLE
Is there a binary out there?

### ISSUE THREAD

**Issue by rufus42** [younata/mdbook-chapter-path#1]
Hello @younata,

sounds great!
Unfortunately I can't install Rust.
Is there a binary out there?

Thanks & greetings
rufus42

**Comment by younata** [comment]
Not really. It's not one of my needs to set up the infrastructure for doing cross compilation, so this is only available as a source distribution.

The closest I can point you to is a [docker image I maintain](https://hub.docker.com/r/younata/personal-knowledge-builder) for the purposes of building my [digital garden](https://knowledge.rachelbrindle.com) that has mdbook-chapter-path installed (as well as [everything else I use](https://knowledge.rachelbrindle.com/meta/tooling.html) to build my digital garden). You can use that image to call mdbook-chapter-path, but that would be a bit of a hack.

Sorry.

**Comment by rufus42** [comment]
Hello @younata,

thank you very much for your time and your answer.

Thanks also for the Docker hint.
Working with Docker is (currently) beyond my capabilities.

Many greetings
rufus42
